### PR TITLE
Read ASN from server-timings and ship it to metrics

### PR DESCRIPTION
**Pull request by ierceg**

### CODE REVIEW

**Review by petrvecera — APPROVED** [review]
Looks good, let us know when we should ship this @ierceg  👍

**Comment by ierceg** [comment]
Could you check in a browsers that it actually works? :D


Ivan Erceg
*SR director engineering*

D  +56.9.9333.0367 <+56+9+9333+0367>     |     E  ***@***.***
[image: Edgio] <https://edg.io>
DELIVERING UNMATCHED DIGITAL EXPERIENCES AT THE EDGE

Sent via Superhuman ***@***.***>

**Comment by negyxo** [comment]
@ierceg seems to work :)

Here is the small test:
https://aleksandar-perkucin-58-my-app-default.layer0-limelight.link/

image

**Comment by negyxo** [comment]
I think this is related to layer0 only, as these are mappings for layer0 only, but let's wait for @ierceg to confirm.

**Comment by negyxo** [comment]
Here is the test on v7:
image
and here is the link (perma link, for some reason behind the edge deployments don't work on staging)
https://aleksandar-perkucin-rum-test-4.free.edgio-stage-perma.link/rum

**Pull request merged**
